function q(s){return document.querySelector(s)}
function cpuCard(x){return `<article class="card"><div class="brand">${x[0]}</div><h3>${x[1]}</h3><div class="spec"><span>${x[2]}C / ${x[3]}T</span><span>${x[4]}W</span><span>${x[5]}</span></div><div class="score"><b>${x[6]}</b><small>GAMING SCORE</small></div><button onclick="selectCPU('${x[1]}')">Compare</button></article>`}
function gpuCard(x){return `<article class="card"><div class="brand">${x[0]}</div><h3>${x[1]}</h3><div class="spec"><span>${x[2]}GB VRAM</span><span>${x[3]}W</span><span>${x[4]}</span></div><div class="score"><b>${x[5]}</b><small>GAMING SCORE</small></div><button onclick="selectGPU('${x[1]}')">Compare</button></article>`}
function renderCPU(){let qv=q("#cpuSearch").value.toLowerCase(),br=q("#cpuBrand").value,a=HW_DATA.cpus.filter(x=>(br=="All brands"||x[0]==br)&&x[1].toLowerCase().includes(qv));a.sort((x,y)=>q("#cpuSort").value=="Year"?y[5]-x[5]:y[6]-x[6]);q("#cpuGrid").innerHTML=a.map(cpuCard).join("")}
function renderGPU(){let qv=q("#gpuSearch").value.toLowerCase(),br=q("#gpuBrand").value,a=HW_DATA.gpus.filter(x=>(br=="All brands"||x[0]==br)&&x[1].toLowerCase().includes(qv));a.sort((x,y)=>q("#gpuSort").value=="VRAM"?y[2]-x[2]:q("#gpuSort").value=="Year"?y[4]-x[4]:y[5]-x[5]);q("#gpuGrid").innerHTML=a.map(gpuCard).join("")}
["#cpuSearch","#cpuBrand","#cpuSort"].forEach(s=>q(s).oninput=renderCPU);["#gpuSearch","#gpuBrand","#gpuSort"].forEach(s=>q(s).oninput=renderGPU);
function fill(){q("#cpuA").innerHTML=HW_DATA.cpus.map(x=>`<option>${x[1]}</option>`).join("");q("#cpuB").innerHTML=HW_DATA.cpus.map(x=>`<option>${x[1]}</option>`).join("");q("#gpuA").innerHTML=HW_DATA.gpus.map(x=>`<option>${x[1]}</option>`).join("");q("#gpuB").innerHTML=HW_DATA.gpus.map(x=>`<option>${x[1]}</option>`).join("");updateFPS()}
function selectCPU(n){q("#cpuA").value=n;location.hash="compare";compareCPU()}function selectGPU(n){q("#gpuA").value=n;location.hash="compare";compareGPU()}
function compareCPU(){let a=HW_DATA.cpus.find(x=>x[1]==q("#cpuA").value),b=HW_DATA.cpus.find(x=>x[1]==q("#cpuB").value);if(!a||!b)return;let fa=HW_DATA.cpu_fps[a[1]],fb=HW_DATA.cpu_fps[b[1]];q("#compareOut").innerHTML=`<div class="result"><div><small>CPU A</small><h3>${a[1]}</h3><strong>${a[6]}</strong><p>${a[2]} cores / ${a[3]} threads · ${a[4]}W</p></div><div><small>CPU B</small><h3>${b[1]}</h3><strong>${b[6]}</strong><p>${b[2]} cores / ${b[3]} threads · ${b[4]}W</p></div><div class="HW_DATA.games"><b>REFERENCE FPS</b>${HW_DATA.games.map((g,i)=>`<p><span>${g}</span><em>${fa[i]} vs ${fb[i]} FPS</em></p>`).join("")}</div></div>`}
function compareGPU(){let a=HW_DATA.gpus.find(x=>x[1]==q("#gpuA").value),b=HW_DATA.gpus.find(x=>x[1]==q("#gpuB").value);if(!a||!b)return;let fa=HW_DATA.gpu_fps[a[1]],fb=HW_DATA.gpu_fps[b[1]];q("#compareOut").innerHTML=`<div class="result"><div><small>GPU A</small><h3>${a[1]}</h3><strong>${a[5]}</strong><p>${a[2]}GB VRAM · ${a[3]}W</p></div><div><small>GPU B</small><h3>${b[1]}</h3><strong>${b[5]}</strong><p>${b[2]}GB VRAM · ${b[3]}W</p></div><div class="HW_DATA.games"><b>REFERENCE FPS</b>${HW_DATA.games.map((g,i)=>`<p><span>${g}</span><em>${fa[i]} vs ${fb[i]} FPS</em></p>`).join("")}</div></div>`}
function updateFPS(){let type=q("#fpsType").value,list=type=="CPU"?HW_DATA.cpus:HW_DATA.gpus;q("#fpsPart").innerHTML=list.map(x=>`<option>${x[1]}</option>`).join("");renderFPS()}
function renderFPS(){let type=q("#fpsType").value,n=q("#fpsPart").value,arr=type=="CPU"?HW_DATA.cpu_fps[n]:HW_DATA.gpu_fps[n];q("#fpsTable").innerHTML=`<div class="fps-title">${n} — REFERENCE GAMING FPS</div>`+HW_DATA.games.map((g,i)=>`<div class="fps-row"><span>${g}</span><b>${arr[i]} FPS</b></div>`).join("")}
q("#fpsType").onchange=updateFPS;q("#fpsPart").onchange=renderFPS;
renderCPU();renderGPU();fill();
